Repository SOPT-FROZEN/client, pull requests merged in 2022-11, with the labels that each got.

#1 [빌드작업] 색상 파일 추가, 페이지 추가 및 라우팅 수정
  src/Router.tsx
  src/pages/CartPage.tsx
  src/pages/DetailPage.tsx
  src/pages/ExPage.tsx
  src/pages/MainPage.tsx
  src/pages/PayPage.tsx
  src/styles/colors.ts
Labels: 빌드작업

#15 Refactor : style rem으로 지정
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
Labels: 🛠 리팩터링

#19 [ 리팩토링 ] styled components 옮기기, 개별요소 선언하기, px to rem
  src/App.tsx
  src/assets/image/asset.tsx
  src/components/CartPage/AddressAndTime.tsx
  src/components/CartPage/CardContent/CardFooter.tsx
  src/components/CartPage/CardContent/CardHeader.tsx
  src/components/CartPage/CardContent/CardMenu.tsx
  src/components/CartPage/Cards.tsx
  src/components/common/Header.tsx
  src/pages/CartPage.tsx
Labels: 🛒 장바구니

#18 [ Fix ] 수량변경 공용 컴포넌트 Counter
  src/components/CartPage/CardContent/CardFooter.tsx
  src/components/CartPage/CardContent/CardHeader.tsx
  src/components/CartPage/Cards.tsx
  src/components/common/Counter.tsx
  src/pages/CartPage.tsx
Labels: 🛠 리팩터링

#25 [ Refactor ] 메인페이지 px to rem으로 수정, 화면 깨짐 수정, 오타 수정
  .vscode/extensions.json
  src/components/MainPage/Filter.tsx
  src/components/MainPage/Memu.tsx
  src/components/MainPage/Menu.tsx
  src/pages/MainPage.tsx
Labels: 🏡 메인페이지

#23 [ FIX ] : allergy data map하는 공용컴포넌트로 분리
  src/assets/image/asset.tsx
  src/assets/image/icon_chicken.png
  src/assets/image/icon_cow.png
  src/assets/image/icon_letture.png
  src/assets/image/icon_pig.png
  src/assets/image/icon_tomato.png
  src/components/MainPage/Menu.tsx
  src/components/common/Allergy.tsx
  src/pages/DetailPage.tsx
  src/pages/MainPage.tsx
Labels: 🛠 리팩터링

#32 [ 장바구니 페이지 ] 페이지 이동버튼 기능 구현
  src/components/CartPage/CardContent/CardFooter.tsx
  src/components/common/Counter.tsx
  src/pages/CartPage.tsx
Labels: 🛒 장바구니

#40 [ 라우터 ] 404 에러 페이지 추가
  src/Router.tsx
  src/components/MainPage/Filter.tsx
  src/components/MainPage/Menu.tsx
  src/pages/Error404.tsx
  src/pages/MainPage.tsx
  src/util/api.ts
Labels: 🚩 라우터

#43 [ 리팩토링 ] 글꼴이 윈도우에서 되지 않는 문제 해결
  src/assets/asset.d.ts
  src/assets/fonts/AppleSDGothicNeoR.woff
  src/styles/GlobalStyle.tsx
Labels: 🛠 리팩터링

#36 [ 결제페이지 ] 장바구니 getAPI 이용해 결제정보 렌더링하기
  src/components/CartPage/Cards.tsx
  src/pages/CartPage.tsx
  src/pages/PayPage.tsx
Labels: 💳 결제페이지

#39 [ 메인페이지 ] 카테고리별 메뉴 GET API 및 디테일 페이지와 연동
  src/components/MainPage/Menu.tsx
Labels: 🏡 메인페이지

#46 [ 메인페이지 ] 메인페이지 장바구니 GET , 주문버튼 활성화
  src/pages/MainPage.tsx
Labels: 🏡 메인페이지

#49 [ 메인페이지 ]디테일 페이지에서 장바구니 담으면 메인페이지에서 토스트메시지 띄우기
  src/components/MainPage/Menu.tsx
  src/index.tsx
  src/pages/DetailPage.tsx
  src/pages/MainPage.tsx
  src/styles/theme.ts
  src/util/api.ts
Labels: 🏡 메인페이지

#51 [메인페이지] 폰트 깨짐 수정
  src/components/MainPage/Menu.tsx
  src/pages/MainPage.tsx
Labels: 🏡 메인페이지
